### ISSUE TITLE
mitogen.core.ChannelError

### ISSUE THREAD

**Issue by kathyl21** [mitogen-hq/mitogen#1029]
I have an ansible playbook that seems to run fine on some hosts and not on others.  This morning I got the following error:

`mitogen.core.ChannelError: the respondent Context has disconnected.`

I'm using mitogen 3.3 and Ansible core 2.2.10. Python version is 3.92. I'm running from a Debian 11 host.

**Comment by arrfab** [comment]
Wanted to create an issue for this but I just hit the same error with mitogen 0.3.7, ansible-core 2.14.14 (python version = 3.9.18)

```

ERROR! [task 154152] 14:29:50.303138 E mitogen: broker crashed
Traceback (most recent call last):
  File "/var/lib/ansible-staging/mitogen/mitogen/core.py", line 3758, in _do_broker_main
    self._loop_once()
  File "/var/lib/ansible-staging/mitogen/mitogen/core.py", line 3713, in _loop_once
    for side, func in self.poller.poll(timeout):
  File "/var/lib/ansible-staging/mitogen/mitogen/core.py", line 2635, in _poll
    (rfds, wfds, _), _ = io_op(select.select,
  File "/var/lib/ansible-staging/mitogen/mitogen/core.py", line 599, in io_op
    return func(*args), None
ValueError: filedescriptor out of range in select()
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: mitogen.core.ChannelError: Broker has exitted
fatal: [host.stg.domain.org]: FAILED! => {"msg": "Unexpected failure during module execution: Broker has exitted", "stdout": ""}
ERROR! [task 154153] 14:29:50.327965 E mitogen: broker crashed

```

**Comment by arrfab** [comment]
@moreati : fwiw, patched 0.3.7 tag/release with https://github.com/mitogen-hq/mitogen/pull/984/files and symptom disappeared (all running fine). I'll keep testing (staging env here) and report/give feedback here

**Comment by ohdearaugustin** [comment]
I have the same issue. I also used the mentioned patch and everything is working again.

Please merge #984
