### ISSUE TITLE
'dnf' dies with dnf5-backend

### ISSUE THREAD

**Issue by philfry** [mitogen-hq/mitogen#1077]
Hi,

I just ran into this problem after switching from dnf3 to dnf5 in my Fedora machines.

Preparation: install python3-dnf5 on the managed host
Playbook:
```yaml
---
- hosts: ansible-test-100
  tasks:
    - dnf: use_backend=dnf5 name=bash,glibc
    - dnf: use_backend=dnf5 name=foo,bar state=absent
```

Backtrace:
```
Traceback (most recent call last):
  File "master:/.../mitogen/ansible_mitogen/runner.py", line 1056, in _run
    self._run_code(code, mod)
  File "master:/.../mitogen/ansible_mitogen/runner.py", line 1020, in _run_code
    exec(code, vars(mod))
  File "master:/usr/lib/python3.12/site-packages/ansible/modules/dnf5.py", line 717, in <module>
  File "master:/usr/lib/python3.12/site-packages/ansible/modules/dnf5.py", line 713, in main
  File "master:/usr/lib/python3.12/site-packages/ansible/modules/dnf5.py", line 521, in run
  File "/usr/lib64/python3.12/site-packages/libdnf5/logger.py", line 459, in __init__
    _logger.GlobalLogger_swiginit(self, _logger.new_GlobalLogger())
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: libdnf5/logger/global_logger.cpp:33: libdnf5::GlobalLogger::GlobalLogger(): API Assertion 'librepo_logger == nullptr' failed: Only one GlobalLogger can exist at a time
```

The problem doesn't show up if you have only one `dnf` task.

* Which version of Ansible are you running? → 2.16.6
* Have you tried the latest master version from Git? → yes
* Mention your host and target OS and versions → Fedora 39
* Mention your host and target Python versions → 3.12.3
* If reporting a crash or hang in Ansible, please rerun with -vvv and include
  200 lines of output around the point of the error, along with a full copy of
  any traceback or error text in the log. Beware "-vvv" may include secret
  data! Edit as necessary before posting.
[dnf5.bt.txt](https://github.com/mitogen-hq/mitogen/files/15331291/dnf5.bt.txt)

**Comment by sven76** [comment]
* Ansible Version: 2.19.4 (Debian 13)
* Mitogen: 0.3.25
* Python: 3.13.5

As a workaround until a appropriate solution is found. I created a patch for the dnf5 module of Ansible:

```diff
--- dnf5.py.orig        2026-01-14 17:44:45.581856326 +0000
+++ dnf5.py     2026-01-15 09:29:47.395762925 +0000
@@ -625,7 +625,23 @@
         self.fail_on_non_existing_plugins(base)
 
         log_router = base.get_logger()
-        global_logger = libdnf5.logger.GlobalLogger()
+        global_logger = None
+        try:
+            global_logger = libdnf5.logger.GlobalLogger()
+        except Exception as e:
+            if "Only one GlobalLogger can exist" in str(e):
+                class DummyGlobalLogger:
+                    def set(self, *args, **kwargs):
+                        pass
+                    def __getattr__(self, name):
+                        def dummy_method(*args, **kwargs):
+                            pass
+                        return dummy_method
+                global_logger = DummyGlobalLogger()
+            else:
+                raise
         global_logger.set(log_router.get(), libdnf5.logger.Logger.Level_DEBUG)
         # FIXME hardcoding the filename does not seem right, should libdnf5 expose the default file name?
         logger = libdnf5.logger.create_file_logger(base, "dnf5.log")
```

**Comment by moreati** [comment]
Reproduced, for some reason happens on the third invocation

```
➜  mitogen git:(master) ✗ ANSIBLE_STRATEGY_PLUGINS=~/src/mitogen/ansible_mitogen/plugins/strategy ANSIBLE_STRATEGY=mitogen_linear ansible-playbook -i 192.168.64.11, -e ansible_become_pass=*** issue1539.yml

PLAY [all] *****************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************
[WARNING]: Platform linux on host 192.168.64.11 is using the discovered Python interpreter at /usr/bin/python3.12, but
future installation of another Python interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-core/2.18/reference_appendices/interpreter_discovery.html for more information.
ok: [192.168.64.11]

TASK [debug] ***************************************************************************************************************
ok: [192.168.64.11] => {
    "msg": "Fedora 39"
}

TASK [ansible.builtin.dnf] *************************************************************************************************
ok: [192.168.64.11]

TASK [ansible.builtin.dnf] *************************************************************************************************
ok: [192.168.64.11]

TASK [ansible.builtin.dnf] *************************************************************************************************
fatal: [192.168.64.11]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3.12"}, "changed": false, "failures": [], "msg": "libdnf5/logger/global_logger.cpp:33: libdnf5::GlobalLogger::GlobalLogger(): API Assertion 'librepo_logger == nullptr' failed: Only one GlobalLogger can exist at a time", "rc": 1}

PLAY RECAP *****************************************************************************************************************
192.168.64.11              : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

```yaml
- hosts: all
  become: true
  tasks:
    - debug: 
        msg: "{{ ansible_facts.distribution }} {{ ansible_facts.distribution_version}}"

    - ansible.builtin.dnf:
        name:
          - dos2unix
        use_backend: dnf5

    - ansible.builtin.dnf:
        name:
          - dos2unix
        use_backend: dnf5

    - ansible.builtin.dnf:
        name:
          - dos2unix
        use_backend: dnf5
```
