### ISSUE TITLE
DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead

### ISSUE THREAD

**Issue by moreati** [mitogen-hq/mitogen#1111]
A few cases in mitogen.master

```console
$ ag pkgutil.find_loader
mitogen/master.py
187:        loader = pkgutil.find_loader(fullname)
533:        Find `fullname` using :func:`pkgutil.find_loader`.
540:            loader = pkgutil.find_loader(fullname)
554:            # - get_filename() may throw ImportError if pkgutil.find_loader()
```

Seen when running the test suite, e.g.

```
test_prefix_authorized_abspath_bad (file_service_test.FetchTest.test_prefix_authorized_abspath_bad) ... /home/runner/work/mitogen/mitogen/mitogen/master.py:540: DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
  loader = pkgutil.find_loader(fullname)
ok
```

**Comment by moreati** [comment]
For a top level module that doesn't exist both return None
```pycon
>>> pkgutil.find_loader('foobar')
<stdin>:1: DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
>>> importlib.util.find_spec('foobar')
```
for a module in a package that doesn't exist they raise slight different exceptions
```python-repl
>>> pkgutil.find_loader('foobar.baz')
Traceback (most recent call last):
  File "/Users/alex/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/pkgutil.py", line 309, in find_loader
    spec = importlib.util.find_spec(fullname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 91, in find_spec
ModuleNotFoundError: No module named 'foobar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alex/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/pkgutil.py", line 315, in find_loader
    raise ImportError(msg.format(fullname, type(ex), ex)) from ex
ImportError: Error while finding loader for 'foobar.baz' (<class 'ModuleNotFoundError'>: No module named 'foobar')
>>> importlib.util.find_spec('foobar.baz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib.util>", line 91, in find_spec
ModuleNotFoundError: No module named 'foobar'
```

**Comment by moreati** [comment]
The cryptography package overwrites the in memory `types.ModuleType` instance with `cryptography.utils.-ModuleWithDeprecations` if the module in question contains deprecated types declared with `cryptography.utils.deprecated`. This results in `__spec__` having the value `None`, e.g.

```
➜  cryptography git:(main) .venv/bin/python
Python 3.13.0 (main, Oct 16 2024, 08:05:40) [Clang 18.1.8 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cryptography.hazmat.primitives.ciphers.algorithms
>>> cryptography.hazmat.primitives.ciphers.algorithms.__spec__
>>> cryptography.hazmat.primitives.ciphers.algorithms
<module 'cryptography.hazmat.primitives.ciphers.algorithms' from '/Users/alex/src/cryptography/.venv/lib/python3.13/site-packages/cryptography/hazmat/primitives/ciphers/algorithms.py'>
>>> type(cryptography.hazmat.primitives.ciphers.algorithms)
<class 'cryptography.utils._ModuleWithDeprecations'>
>>> import importlib.util
>>> importlib.util.find_spec('cryptography.hazmat.primitives.ciphers.algorithms')
Traceback (most recent call last):
  File "<python-input-5>", line 1, in <module>
    importlib.util.find_spec('cryptography.hazmat.primitives.ciphers.algorithms')
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 111, in find_spec
ValueError: cryptography.hazmat.primitives.ciphers.algorithms.__spec__ is None
```

See
- https://github.com/pyca/cryptography/blob/44.0.0/src/cryptography/hazmat/primitives/ciphers/algorithms.py#L80-L89
- https://github.com/pyca/cryptography/blob/44.0.0/src/cryptography/utils.py#L62-L102
