### ISSUE TITLE
Sporadic EAGAIN errors due to non-blocking stdout

### ISSUE THREAD

**Issue by apyrgio** [mitogen-hq/mitogen#712]
When using Mitogen, I sometimes see `EAGAIN` errors, due to stdout being non-blocking. This breaks the Python interpreter, as well as any other spawned commands, since they don't handle non-blocking file descriptors. To trigger this, one can simply do `sys.stdout.write("A" * 1000000)` on the remote, which will fill the kernel buffer and return `EAGAIN`, instead of blocking.

Reading the sections on ["Standard IO Redirection"] and ["The IO Multiplexer"], my understanding is that Mitogen replaces stdout with a Unix pipe. It gives the write end of the Unix pipe to the Python interpreter, and the read end to a poller (the I/O multiplexer). I understand that the read end typically needs to be non-blocking, else the I/O multiplexer is not fully async. However, I don't see why the write end (what the interpreter perceives as stdout) needs to be non-blocking as well, since it breaks the assumptions of many programs.

So, my question is, is stdout non-blocking by design, or is it a bug? If it's the former, what's the rationale behind it?

["Standard IO Redirection"]: https://mitogen.networkgenomics.com/howitworks.html#standard-io-redirection
["The IO Multiplexer"]: https://mitogen.networkgenomics.com/howitworks.html#the-io-multiplexer

**Comment by dw** [comment]
This is/was an old bug at least in the Ansible extension, I definitely remember fixing it and even have an inkling of writing a test for it.

If you're using the core library, it's possible the problem was fixed in the wrong place, which is why you're still seeing it

**Comment by apyrgio** [comment]
Hi @dw. Quick question, did you manage to reproduce it with the above script?

**Comment by moreati** [comment]
Confirm this is still a problem in latest Mitogen. #1185 may or may not be related. 

```python
import argparse
import sys

import mitogen


def shout(num):
    sys.stdout.write("A" * num)


@mitogen.main()
def main(router):
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--python', default='python3')
    parser.add_argument('hostname')
    parser.add_argument('num', type=int)
    args = parser.parse_args()

    context = router.ssh(hostname=args.hostname, python_path=args.python)
    context.call(shout, args.num)

    print("Passed. Try with a larger payload, e.g., 1000000")
```

```console
➜  mitogen git:(issue1185-blockingioerror) ✗ python3 issue713_repro.py pve.lan 1_000_000
21:47:20.520557 E mitogen: <Side of default fd 3>: flags=0 nonblock=0
21:47:20.520637 E mitogen: <Side of default fd 4>: flags=1 nonblock=0
21:47:20.524203 E mitogen: Latch(0x1036ffcd0, size=0, t='MainThread'): rsock=<socket.socket fd=6, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>, rsock.getblockiung()=True, rsock_fd_flags=2, wsock=<socket.socket fd=7, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>, wsock.getblockiung()=True, wsock_fd_flags=2
21:47:20.598835 E mitogen: <Side of ssh.pve.lan fd 8>: flags=2 nonblock=0
21:47:20.598997 E mitogen: <Side of ssh.pve.lan fd 8>: flags=6 nonblock=1
21:47:20.599058 E mitogen: <Side of ssh.pve.lan fd 10>: flags=0 nonblock=0
21:47:20.599083 E mitogen: <Side of ssh.pve.lan fd 10>: flags=4 nonblock=1
21:47:20.942921 E mitogen.[ssh.pve.lan]: <Side of stdout fd 7>: flags=2 nonblock=0
21:47:20.943053 E mitogen.[ssh.pve.lan]: <Side of stdout fd 8>: flags=2 nonblock=0
21:47:20.943108 E mitogen.[ssh.pve.lan]: <Side of stderr fd 9>: flags=2 nonblock=0
21:47:20.943270 E mitogen.[ssh.pve.lan]: <Side of stderr fd 10>: flags=2 nonblock=0
21:47:20.943332 E mitogen.[ssh.pve.lan]: Latch(0x7a0247c09c50, size=0, t='MainThread'): rsock=<socket.socket fd=11, family=1, type=1, proto=0>, rsock.getblockiung()=True, rsock_fd_flags=2, wsock=<socket.socket fd=12, family=1, type=1, proto=0>, wsock.getblockiung()=True, wsock_fd_flags=2
Traceback (most recent call last):
  File "/Users/alex/src/mitogen/issue713_repro.py", line 12, in <module>
    def main(router):
  File "/Users/alex/src/mitogen/mitogen/__init__.py", line 115, in wrapper
    return mitogen.core._profile_hook(
  File "/Users/alex/src/mitogen/mitogen/core.py", line 697, in _profile_hook
    return func(*args)
  File "/Users/alex/src/mitogen/mitogen/utils.py", line 151, in run_with_router
    return func(router, *args, **kwargs)
  File "/Users/alex/src/mitogen/issue713_repro.py", line 20, in main
    context.call(shout, args.num)
  File "/Users/alex/src/mitogen/mitogen/parent.py", line 2015, in call
    return self.default_call_chain.call(fn, *args, **kwargs)
  File "/Users/alex/src/mitogen/mitogen/parent.py", line 1972, in call
    return receiver.get().unpickle(throw_dead=False)
  File "/Users/alex/src/mitogen/mitogen/core.py", line 1027, in unpickle
    raise obj
mitogen.core.CallError: builtins.BlockingIOError: [Errno 11] write could not complete without blocking
  File "<stdin>", line 3918, in _dispatch_one
  File "master:/Users/alex/src/mitogen/issue713_repro.py", line 8, in shout
    sys.stdout.write("A" * num)
```

**Comment by moreati** [comment]
On the Linux target I'm testing with payloads >= 223361 bytes trigger EAGAIN
```console
➜  mitogen git:(issue712-stdout-non-blocking) ✗ python3 issue713_repro.py pve.lan 223360 
Passed. Try with a larger payload, e.g., 1000000
➜  mitogen git:(issue712-stdout-non-blocking) ✗ python3 issue713_repro.py pve.lan 223361
Traceback (most recent call last):
  File "/Users/alex/src/mitogen/issue713_repro.py", line 17, in <module>
    def main(router):
  File "/Users/alex/src/mitogen/mitogen/__init__.py", line 115, in wrapper
    return mitogen.core._profile_hook(
  File "/Users/alex/src/mitogen/mitogen/core.py", line 685, in _profile_hook
    return func(*args)
  File "/Users/alex/src/mitogen/mitogen/utils.py", line 151, in run_with_router
    return func(router, *args, **kwargs)
  File "/Users/alex/src/mitogen/issue713_repro.py", line 25, in main
    context.call(shout, args.num)
  File "/Users/alex/src/mitogen/mitogen/parent.py", line 2015, in call
    return self.default_call_chain.call(fn, *args, **kwargs)
  File "/Users/alex/src/mitogen/mitogen/parent.py", line 1972, in call
    return receiver.get().unpickle(throw_dead=False)
  File "/Users/alex/src/mitogen/mitogen/core.py", line 1015, in unpickle
    raise obj
mitogen.core.CallError: builtins.BlockingIOError: [Errno 11] write could not complete without blocking
  File "<stdin>", line 3888, in _dispatch_one
  File "master:/Users/alex/src/mitogen/issue713_repro.py", line 13, in shout
    sys.stdout.write('A' * num)
```

**Comment by moreati** [comment]
@apyrgio sorry for the _very_ long wait on this ticket. If you're still using Mitogen, then you may like to try the moreati:issue712-stdout-non-blocking, the branch in PR ~~#1306~~ #1300 that I believe fixes this issue. Thanks, Alex

Edit: corrected PR number
