### ISSUE TITLE
AttributeError: 'zlib.Compress' object has no attribute 'copy'

### ISSUE THREAD

**Issue by xiaopeng163** [mitogen-hq/mitogen#768]
## Environments

Ansible 2.8.18 + py3.7

```
$ pip freeze
ansible==2.8.18
bcrypt==3.2.0
cffi==1.14.4
cryptography==3.3.1
Jinja2==2.11.2
jmespath==0.10.0
MarkupSafe==1.1.1
paramiko==2.7.2
pycparser==2.20
PyNaCl==1.4.0
PyYAML==5.3.1
six==1.15.0
```

```
$ python
Python 3.7.4 (default, Sep  4 2019, 13:30:03)
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
```

## Re-produce

ansible.cfg

```
[defaults]
host_key_checking = false
command_warnings=False
callback_whitelist = profile_tasks
strategy_plugins = plugin/mitogen-0.2.9/ansible_mitogen/plugins/strategy
strategy = mitogen_linear
```

ansible playbook

```
---
- hosts: all
  gather_facts: no
  any_errors_fatal: True

  tasks:
    - name: get all files name list
      find:
        paths: /etc/telegraf/telegraf.d/
        file_type: file
      register: result
```

Error Message

```
$ ANSIBLE_CONFIG=./ansible.cfg ansible-playbook -i inventories/acceptance/hosts site.yml

PLAY [all] *****************************************************************************************************************************************************************************************************************************************************

TASK [get all files name list] ***********************************************************************************************************************************************************************************************************************************************
Tuesday 29 December 2020  13:56:09 +0100 (0:00:00.996)       0:00:00.996 ******
ERROR! [mux  7845] 13:56:10.485186 E mitogen.service: Pool(9bd0, size=32, th='mitogen.Pool.9bd0.0'): while invoking 'get' of 'ansible_mitogen.services.ContextService'
Traceback (most recent call last):
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/mitogen/service.py", line 621, in _on_service_call
    return invoker.invoke(method_name, kwargs, msg)
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/mitogen/service.py", line 307, in invoke
    response = self._invoke(method_name, kwargs, msg)
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/mitogen/service.py", line 293, in _invoke
    ret = method(**kwargs)
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/ansible_mitogen/services.py", line 489, in get
    reraise(*result)
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/ansible_mitogen/services.py", line 75, in reraise
    raise value
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/ansible_mitogen/services.py", line 447, in _wait_or_start
    response = self._connect(key, spec, via=via)
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/ansible_mitogen/services.py", line 399, in _connect
    context = method(via=via, unidirectional=True, **spec['kwargs'])
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/mitogen/parent.py", line 2502, in ssh
    return self.connect(u'ssh', **kwargs)
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/mitogen/parent.py", line 2444, in connect
    return self._connect(klass, **mitogen.core.Kwargs(kwargs))
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/mitogen/parent.py", line 2424, in _connect
    conn.connect(context=context)
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/mitogen/parent.py", line 1706, in connect
    raise self.exception
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/mitogen/parent.py", line 1681, in _async_connect
    self.proc = self.start_child()
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/mitogen/parent.py", line 1520, in start_child
    args = self.get_boot_command()
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/mitogen/ssh.py", line 293, in get_boot_command
    base = super(Connection, self).get_boot_command()
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/mitogen/parent.py", line 1470, in get_boot_command
    preamble_compressed = self.get_preamble()
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/mitogen/parent.py", line 1509, in get_preamble
    return partial.append(suffix.encode('utf-8'))
  File "/home/penxiao/ansible-demo/plugin/mitogen-0.2.9/mitogen/parent.py", line 711, in append
    compressor = self._compressor.copy()
AttributeError: 'zlib.Compress' object has no attribute 'copy'
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:     compressor = self._compressor.copy()
fatal: [10.1.1.1]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

NO MORE HOSTS LEFT ***********************************************************************************************************************************************************************************************************************************************************

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
10.1.1.1  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Tuesday 29 December 2020  13:56:10 +0100 (0:00:00.708)       0:00:01.705 ******
===============================================================================
get all files name list ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by dw** [comment]
Hi Peng,

What kind of target were you deploying to, and what OS / version of Python is on the target?

Thanks,


David

**Comment by xiaopeng163** [comment]
centos7 and with python2.7&python3 installed

**Comment by dw** [comment]
Thanks for reporting this, and apologies for the delay.

Can you please retry the run using the build below and report whether the problem abates:

* https://github.com/mitogen-hq/mitogen/archive/dmw.zip

The error you received should be 'impossible' on any Python release since 2.5, so I'm thinking this might be some strange patched Python build in use, possibly custom-compiled, or similar. The only alternative I can think of is somehow that code is running during interpreter shutdown, which seems very unlikely

**Comment by xiaopeng163** [comment]
thanks for your reply, and I will try it this week

**Comment by xiaopeng163** [comment]
this time, got an error like this

```
PLAY [all] ******************************************************************************************************************************************************************************************************
ERROR! Unexpected Exception, this is probably a bug: 'PluginLoader' object has no attribute 'get_with_context'
the full traceback was:

Traceback (most recent call last):
  File "/home/penxiao/vir/ansible-2.8/bin/ansible-playbook", line 110, in <module>
    exit_code = cli.run()
  File "/home/penxiao/vir/ansible-2.8/lib/python3.7/site-packages/ansible/cli/playbook.py", line 123, in run
    results = pbex.run()
  File "/home/penxiao/vir/ansible-2.8/lib/python3.7/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/home/penxiao/vir/ansible-2.8/lib/python3.7/site-packages/ansible/executor/task_queue_manager.py", line 230, in run
    strategy = strategy_loader.get(new_play.strategy, self)
  File "/home/penxiao/vir/ansible-2.8/lib/python3.7/site-packages/ansible/plugins/loader.py", line 558, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/home/penxiao/vir/ansible-2.8/lib/python3.7/site-packages/ansible/plugins/loader.py", line 536, in _load_module_source
    module = imp.load_source(to_native(full_name), to_native(path), module_file)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/penxiao/telegraf/plugin/mitogen-dmw/ansible_mitogen/plugins/strategy/mitogen_linear.py", line 55, in <module>
    import ansible_mitogen.loaders
  File "/home/penxiao/telegraf/plugin/mitogen-dmw/ansible_mitogen/loaders.py", line 62, in <module>
    connection_loader__get = connection_loader.get_with_context
AttributeError: 'PluginLoader' object has no attribute 'get_with_context'
```

**Comment by s1113950** [comment]
@xiaopeng163 you need to use Ansible 2.10+ to use @dw 's branch as it's based off of `master` which only supports Ansible 2.10+ at this time.

**Comment by xiaopeng163** [comment]
ok, thanks, it is working now.
