### ISSUE TITLE
test failures: AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by moreati** [mitogen-hq/mitogen#850]
e.g. from https://dev.azure.com/mitogen-hq/mitogen/_build/results?buildId=108&view=logs&jobId=39882f3a-9103-5f46-8b73-c9b5dbece82f&j=364fd14b-95c5-5834-280a-1629ce194374&t=1b0abb5f-92e2-5ce1-22fe-ad8871c3092d

```
======================================================================
ERROR: setUpClass (fakessh_test.RsyncTest)
----------------------------------------------------------------------
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/vsts/work/1/s/tests/testlib.py", line 543, in setUpClass
    cls.dockerized_ssh = DockerizedSshDaemon(**daemon_args)
  File "/home/vsts/work/1/s/tests/testlib.py", line 471, in __init__
    self.start_container()
  File "/home/vsts/work/1/s/tests/testlib.py", line 451, in start_container
    self._get_container_port()
  File "/home/vsts/work/1/s/tests/testlib.py", line 426, in _get_container_port
    dport, proto, baddr, bport = self.PORT_RE.match(line).groups()
AttributeError: 'NoneType' object has no attribute 'groups'

======================================================================
ERROR: setUpClass (su_test.SuTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vsts/work/1/s/tests/testlib.py", line 543, in setUpClass
    cls.dockerized_ssh = DockerizedSshDaemon(**daemon_args)
  File "/home/vsts/work/1/s/tests/testlib.py", line 471, in __init__
    self.start_container()
  File "/home/vsts/work/1/s/tests/testlib.py", line 451, in start_container
    self._get_container_port()
  File "/home/vsts/work/1/s/tests/testlib.py", line 426, in _get_container_port
    dport, proto, baddr, bport = self.PORT_RE.match(line).groups()
AttributeError: 'NoneType' object has no attribute 'groups'

----------------------------------------------------------------------
Ran 645 tests in 47.176s

FAILED (errors=4, skipped=43)
coverage report is at file:///home/vsts/work/1/s/htmlcov/index.html
Command exited with non-zero status 1
36.07user 5.47system 0:49.08elapsed 84%CPU (0avgtext+0avgdata 70596maxresident)k
3144inputs+7672outputs (8major+1262869minor)pagefaults 0swaps
Exception occurred while running: ['/usr/bin/time', '--', './run_tests', '-v']
Traceback (most recent call last):
  File "/home/vsts/work/1/s/.ci/mitogen_tests.py", line 18, in <module>
    ci_lib.run('./run_tests -v')
  File "/home/vsts/work/1/s/.ci/ci_lib.py", line 112, in run
    ret = subprocess.check_call(argv, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/time', '--', './run_tests', '-v']' returned non-zero exit status 1
##[error]Bash exited with code '1'.

    Finishing: Run mitogen_tests.py
```

**Comment by moreati** [comment]
Fixed by #851
