### ISSUE TITLE
AWS S3 module not working with mitogen 0.3.x

### ISSUE THREAD

**Issue by mathewseby** [mitogen-hq/mitogen#864]
* Which version of Ansible are you running?
```
ansible 2.10.0
  config file = /Users/mathewsebastian/.ansible.cfg
  configured module search path = ['/Users/mathewsebastian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mathewsebastian/Library/Python/3.8/lib/python/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Jun  8 2021, 11:59:35) [Clang 12.0.5 (clang-1205.0.22.11)]
```
* Is your version of Ansible patched in any way?
No
* Are you running with any custom modules, or `module_utils` loaded?
No

* Have you tried the latest master version from Git?
Yes
* Do you have some idea of what the underlying problem may be?
  https://mitogen.networkgenomics.com/ansible_detailed.html#common-problems has
  instructions to help figure out the likely cause and how to gather relevant
  logs.
No
* Mention your host and target OS and versions
host: Amazon linux 2 
target: Amazon linux 2, Centos 7
* Mention your host and target Python versions
host: 3.8
target: 2.7

* Describe the bug

AWS s3 module not working with mitogen 0.3.x, the job is running fine when mitogen is disabled. Following is the error message.

```
The full traceback is:
Traceback (most recent call last):
  File "master:/opt/mitogen-0.3.0/ansible_mitogen/runner.py", line 975, in _run
    self._run_code(code, mod)
  File "master:/opt/mitogen-0.3.0/ansible_mitogen/runner.py", line 941, in _run_code
    exec('exec code in vars(mod)')
  File "<string>", line 1, in <module>
  File "master:/Users/mathewsebastian/.ansible/collections/ansible_collections/amazon/aws/plugins/modules/aws_s3.py", line 360, in <module>
SystemError: Parent module 'ansible_collections.amazon.aws.plugins' not loaded, cannot perform relative import
fatal: [13.232.50.214]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"master:/opt/mitogen-0.3.0/ansible_mitogen/runner.py\", line 975, in _run\n    self._run_code(code, mod)\n  File \"master:/opt/mitogen-0.3.0/ansible_mitogen/runner.py\", line 941, in _run_code\n    exec('exec code in vars(mod)')\n  File \"<string>\", line 1, in <module>\n  File \"master:/Users/mathewsebastian/.ansible/collections/ansible_collections/amazon/aws/plugins/modules/aws_s3.py\", line 360, in <module>\nSystemError: Parent module 'ansible_collections.amazon.aws.plugins' not loaded, cannot perform relative import\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by mathewseby** [comment]
@moreati Could you please help with this?

**Comment by mathewseby** [comment]
added import ansible_collections.amazon.aws.plugins [here](https://github.com/mitogen-hq/mitogen/blob/680fa81b22efbe3a07d8c5e049448b4b3bf55ca2/ansible_mitogen/runner.py#L49) and the S3 module is working now.
