### ISSUE TITLE
ERROR! Your version of Ansible ((2, 9, 27)) is too old. The oldest version supported by Mitogen for Ansible is (2, 10).

### ISSUE THREAD

**Issue by lirany1** [mitogen-hq/mitogen#865]
Started to get this error
* Which version of Ansible are you running?
`willhallonline/ansible:2.9-alpine`

```
16:33:11  ERROR! Your version of Ansible ((2, 9, 27)) is too old. The oldest version supported by Mitogen for Ansible is (2, 10).
16:33:11  FATAL: command execution failed
16:33:11  hudson.AbortException: Ansible playbook execution failed
16:33:11  	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:262)
16:33:11  	at org.jenkinsci.plugins.ansible.workflow.AnsiblePlaybookStep$AnsiblePlaybookExecution.run(AnsiblePlaybookStep.java:430)
16:33:11  	at org.jenkinsci.plugins.ansible.workflow.AnsiblePlaybookStep$AnsiblePlaybookExecution.run(AnsiblePlaybookStep.java:351)
16:33:11  	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
16:33:11  	at hudson.security.ACL.impersonate2(ACL.java:449)
16:33:11  	at hudson.security.ACL.impersonate(ACL.java:461)
16:33:11  	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
16:33:11  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
16:33:11  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
16:33:11  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
16:33:11  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
16:33:11  	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by moreati** [comment]
Please double check your version of Mitogen. Version 0.2.10 works for me with Ansible 2.9.27

```
$ python3 -mvenv v
$ v/bin/pip install mitogen==0.2.10 ansible==2.9.27
Collecting mitogen==0.2.10
  Downloading mitogen-0.2.10.tar.gz (215 kB)
     |████████████████████████████████| 215 kB 10.1 MB/s 
Collecting ansible==2.9.27
  Downloading ansible-2.9.27.tar.gz (14.8 MB)
     |████████████████████████████████| 14.8 MB 42.3 MB/s 
Collecting jinja2
  Downloading Jinja2-3.0.2-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 46.2 MB/s 
Collecting PyYAML
  Downloading PyYAML-6.0-cp39-cp39-macosx_11_0_arm64.whl (173 kB)
     |████████████████████████████████| 173 kB 25.5 MB/s 
Collecting cryptography
  Downloading cryptography-35.0.0-cp36-abi3-macosx_11_0_arm64.whl (2.4 MB)
     |████████████████████████████████| 2.4 MB 133.7 MB/s 
Collecting cffi>=1.12
  Downloading cffi-1.15.0-cp39-cp39-macosx_11_0_arm64.whl (173 kB)
     |████████████████████████████████| 173 kB 51.2 MB/s 
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 24.6 MB/s 
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.0.1-cp39-cp39-macosx_10_9_universal2.whl (18 kB)
Using legacy 'setup.py install' for mitogen, since package 'wheel' is not installed.
Using legacy 'setup.py install' for ansible, since package 'wheel' is not installed.
Installing collected packages: pycparser, MarkupSafe, cffi, PyYAML, jinja2, cryptography, mitogen, ansible
    Running setup.py install for mitogen ... done
    Running setup.py install for ansible ... done
Successfully installed MarkupSafe-2.0.1 PyYAML-6.0 ansible-2.9.27 cffi-1.15.0 cryptography-35.0.0 jinja2-3.0.2 mitogen-0.2.10 pycparser-2.20
...
$ ANSIBLE_STRATEGY=mitogen_linear ANSIBLE_STRATEGY_PLUGINS=v/lib/python3.9/site-packages/ansible_mitogen v/bin/ansible localhost -mping 
[WARNING]: No inventory was parsed, only implicit localhost is available
localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```

**Comment by lirany1** [comment]
i checked still same issue

as i am using this dockerfile
https://github.com/willhallonline/docker-ansible/blob/master/ansible29/alpine313/Dockerfile

**Comment by moreati** [comment]
How did you check the version of Mitogen? From what I see of that Dockerfile

```
    pip install mitogen ansible-lint jmespath && \
```
https://github.com/willhallonline/docker-ansible/blob/9a74416040d037f6255ca0a5cbf35d3f7bd8a03c/ansible29/alpine313/Dockerfile#L39

there is no version specified. So pip can choose the highest version, which is 0.3.0, not 0.2.10.

**Comment by lirany1** [comment]
> How did you check the version of Mitogen? From what I see of that Dockerfile
> 
> ```
>     pip install mitogen ansible-lint jmespath && \
> ```
> 
> https://github.com/willhallonline/docker-ansible/blob/9a74416040d037f6255ca0a5cbf35d3f7bd8a03c/ansible29/alpine313/Dockerfile#L39
> 
> there is no version specified. So pip can choose the highest version, which is 0.3.0, not 0.2.10.

So it means that there is an issue as if it installed 0.3.0 on ansible 2.9 it's not supported as mentioned:

```
This release separates itself from the v0.2.X releases. Ansible’s API changed too much to support backwards compatibility so from now on, v0.2.X releases will be for Ansible < 2.10 and v0.3.X will be for Ansible 2.10+. See here for details.

#731 ansible 2.10 support

#652 support for ansible collections import hook
```

**Comment by moreati** [comment]
Correct. In your Dockerfile you need to specify the version of Mitogen you install. You can specify an exact version (`"mitogen==0.2.10"`) like you're doing with for Ansible. Or you can specify a range (`"mitogen>=0.2,<0.3"`).
