### ISSUE TITLE
ci: Ensure password su succeeds fails on macOS + Python 3.9

### ISSUE THREAD

**Issue by moreati** [mitogen-hq/mitogen#885]
Python 3.9 + macOS + Ansible tests fail, e.g. https://dev.azure.com/mitogen-hq/mitogen/_build/results?buildId=281&view=results

```
PLAY [integration/become/su_password.yml] **************************************

TASK [Ensure su password absent but required. _raw_params=whoami] **************
fatal: [target]: FAILED! => 
  msg: 'error occurred on host Mac-1639846751180.local: su password is required'
...ignoring

TASK [assert that=['out.failed', "( ('password is required' in out.msg) or ('password is required' in out.module_stderr) )"], fail_msg=out={{out}}] ***
ok: [target] => changed=false 
  msg: All assertions passed

TASK [Ensure password su incorrect. _raw_params=whoami] ************************
fatal: [target]: FAILED! => 
  msg: 'error occurred on host Mac-1639846751180.local: su password is incorrect'
...ignoring

TASK [assert that=out.failed and (
  ('Incorrect su password' in out.msg) or
  ('su password is incorrect' in out.msg)
)
, fail_msg=out={{out}}] ***
ok: [target] => changed=false 
  msg: All assertions passed

TASK [Ensure password su succeeds. _raw_params=whoami] *************************
fatal: [target]: FAILED! => 
  msg: |-
    error occurred on host Mac-1639846751180.local: EOF on stream; last 100 lines received:
    Password:
    shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/encodings/__init__.py", line 98, in search_function
        mod = __import__('encodings.' + modname, fromlist=_import_tail,
      File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/encodings/base64_codec.py", line 9, in <module>
        import base64
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 925, in _find_spec
      File "<frozen importlib._bootstrap_external>", line 1414, in find_spec
      File "<frozen importlib._bootstrap_external>", line 1383, in _get_spec
      File "<frozen importlib._bootstrap_external>", line 1347, in _path_importer_cache
    PermissionError: [Errno 13] Permission denied
```

Discovered while trying to add an Ansible 5 job on macOS. Affects all Ansible versions supported by 0.3.x, and appears to affect even when `ANSIBLE_STRATEGY=linear`.

**Comment by moreati** [comment]
Seeing this again. Some similarities with https://github.com/ansible/ansible/issues/19729, but ultimately looks like a Python importlib misbehaviour https://github.com/python/cpython/issues/115911
