### ISSUE TITLE
Unsure if Mitogen Running - results not profound

### ISSUE THREAD

**Issue by compumatter** [mitogen-hq/mitogen#893]
Please drag-drop large logs as text file attachments.

With pipelining turned on in both cases, it took my playbook down from: 
* Playbook run took 0 days, 0 hours, 10 minutes, 0 seconds TO
* Playbook run took 0 days, 0 hours, 9 minutes, 20 seconds

That difference is so small that I'm not even sure if Mitogen is playing a role.  I have attached the playbook log file for your consideration.

Ansible is running normally.  Of note, I have set environment variables on both the control and remote server 
  * export MITOGEN_ROUTER_DEBUG=1
  * I have also set this task in my group_vars but still no debug log present for mitogen
  * # set for testing mitogen 
       environment:
          MITOGEN_ROUTER_DEBUG: 1
  But no /tmp/mitogen... debug file is visible on either remote or host though I do see a mitogen_unix_r92rwjqh.sock file appearing on the control while running

I have installed it according to these instructions https://mitogen.networkgenomics.com/ansible_detailed.html#installation

* Which version of Ansible are you running?  2.9.6
* Is your version of Ansible patched in any way? No
* Are you running with any custom modules, or `module_utils` loaded? No
* Using the downloaded https://networkgenomics.com/try/mitogen-0.2.9.tar.gz
* Do you have some idea of what the underlying problem may be? No
* Mention your host and target OS and versions - Ubuntu 20.04 both cases
* Mention your host and target Python versions (2.7.18 on both)

**Comment by compumatter** [comment]
I have just noticed some log file activity pertaining to mitogen-0.2.9 as follows

`Exception ignored in: <function Connection.__del__ at 0x7f0a65b8c700>
Traceback (most recent call last):
  File "/home/ansible/plugins/mitogen-0.2.9/ansible_mitogen/connection.py", line 513, in __del__
    self.close()
  File "/home/ansible/plugins/mitogen-0.2.9/ansible_mitogen/connection.py", line 827, in close
    self._put_connection()
  File "/home/ansible/plugins/mitogen-0.2.9/ansible_mitogen/connection.py", line 808, in _put_connection
    self.chain.reset()
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/parent.py", line 1846, in reset
    self.call_no_reply(mitogen.core.Dispatcher.forget_chain, saved)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/parent.py", line 1901, in call_no_reply
    self.context.send(self.make_msg(fn, *args, **kwargs))
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 2272, in send
    self.router.route(msg)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3345, in route
    self.broker.defer(self._async_route, msg)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 2826, in defer
    raise Error(self.broker_shutdown_msg)
mitogen.core.Error: An attempt was made to enqueue a message with a Broker that has already exitted. It is likely your program called Broker.shutdown() too early.
Exception ignored in: <function Connection.__del__ at 0x7f0a65b8c700>
Traceback (most recent call last):
  File "/home/ansible/plugins/mitogen-0.2.9/ansible_mitogen/connection.py", line 513, in __del__
    self.close()
  File "/home/ansible/plugins/mitogen-0.2.9/ansible_mitogen/connection.py", line 827, in close
    self._put_connection()
  File "/home/ansible/plugins/mitogen-0.2.9/ansible_mitogen/connection.py", line 808, in _put_connection
    self.chain.reset()
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/parent.py", line 1846, in reset
    self.call_no_reply(mitogen.core.Dispatcher.forget_chain, saved)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/parent.py", line 1901, in call_no_reply
    self.context.send(self.make_msg(fn, *args, **kwargs))
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 2272, in send
    self.router.route(msg)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3345, in route
    self.broker.defer(self._async_route, msg)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 2826, in defer
    raise Error(self.broker_shutdown_msg)
mitogen.core.Error: An attempt was made to enqueue a message with a Broker that has already exitted. It is likely your program called Broker.shutdown() too early.
`

**Comment by compumatter** [comment]
I had some suspicions that a Python version issue might be at play.  So I inserted the following in ansible.cfg [default] section 
[defaults]
interpreter_python = /usr/bin/Python-3.7.0

This cleared up the above log errors. 

I have also noticed the following appearing in the playbook.log file:
```
2022-01-12 15:56:51,732 p=11192 u=ansible n=ansible | Using /home/ansible/playbooks/ansible.cfg as config file
2022-01-12 15:56:52,415 p=11192 u=ansible n=ansible | PLAY [fresh_installs] *******************************************************************************************************************************************************************************************************************************************************
2022-01-12 15:56:52,489 p=11192 u=ansible n=ansible_mitogen.runner | EnvironmentFileWatcher('/home/ansible/.pam_environment') installed; existing keys: []
2022-01-12 15:56:52,491 p=11192 u=ansible n=**ansible_mitogen**.runner | EnvironmentFileWatcher('/etc/environment') installed; existing keys: [b'PATH', b'RCLONE_CONFIG', b'MYSQL_ROOT_PWD', b'DEV_SERVER']
```
and am in fact noticing the word 'mitogen' appearing through the log file ie;
`2022-01-12 15:57:02,509 p=11192 u=ansible n=ansible | changed: [cmcmatter.biz] => {"changed": true, "checksum": "4a2c76b288f862e6ca5aab436c1c4a9c4f9db285", "dest": "/SM/partion_n_label_all.sh", "gid": 0, "group": "root", "md5sum": "d2fb9ba82311998a88e3b7ca464632cc", "mode": "0755", "owner": "root", "size": 5804, "src": "/root/.ansible/tmp/**ansible_mitogen_action_5a977c0c3896ea08**/source", "state": "file", "uid": 0}`

and

`"..../home/ansible/globals/etc/apache2", "size": 440, "src": "/home/ansible/globals/etc/apache2/mods-available/SM_fastcgi.conf", "state": "file", "uid": 1022}, "md5sum": "5ad97930b98e43aef963516f6aa2b8f5", "mode": "0644", "owner": "root", "size": 426, "src": "/root/.ansible/tmp/**ansible_mitogen_action_706d4027947be3cf**/source", "state": "file", "uid": 0}`

So I am under the impression that mitogen is actually being used now.  However, the time it takes to run the playbook is virtually unchanged from running without mitogen.  

Any thoughts on this?

Thanks.

**Comment by compumatter** [comment]
Logs that are generated to the screen after running the playbook

```
Tuesday 18 January 2022  20:21:16 -0800 (0:00:00.180)       0:10:40.005 *******
===============================================================================
fresh_installs : only_office_doc_server ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 69.90s
fresh_installs : cm_plugins_needed ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 36.30s
fresh_installs : nextcloud_unpack ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 29.94s
fresh_installs : Install dependencies --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 22.98s
fresh_installs : Remove all samba packages ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 21.94s
fresh_installs : install_via_occ_command ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 21.07s
fresh_installs : install_php_pkgs ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 18.27s
fresh_installs : purge_nginx_common ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 16.59s
fresh_installs : install apache2 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 16.47s
fresh_installs : purge_lib_apache_mod --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 16.34s
fresh_installs : purge_apache ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 14.97s
fresh_installs : install nginx-extras --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 12.14s
fresh_installs : install cloudflare plugin for certbot's wildcard ssl -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 9.40s
fresh_installs : purge remove existing python3-acme -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 8.61s
fresh_installs : install latest certbot from https://ubuntu.pkgs.org/.... ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 8.39s
fresh_installs : purge remove existing certbot ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 8.13s
Gathering Facts -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 8.08s
fresh_installs : get setup script -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 7.70s
fresh_installs : Install pip3 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 7.49s
fresh_installs : Start domain provisioning ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 7.21s
Playbook run took 0 days, 0 hours, 10 minutes, 39 seconds
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 572, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 541, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 384, in format
    return self._fmt % record.__dict__
KeyError: 'user'
Call stack:
  File "/usr/local/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3567, in _broker_main
    _profile_hook('mitogen.broker', self._do_broker_main)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 633, in _profile_hook
    return func(*args)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3554, in _do_broker_main
    self._broker_shutdown()
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3533, in _broker_shutdown
    self._loop_once(max(0, deadline - now()))
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3506, in _loop_once
    self._call(side.stream, func)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3481, in _call
    func(self)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 1705, in on_receive
    self.protocol.on_receive(broker, buf)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 2092, in on_receive
    while self._receive_one(broker):
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 2148, in _receive_one
    self._router._async_route(msg, self.stream)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3308, in _async_route
    return self._invoke(msg, in_stream)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3248, in _invoke
    fn(msg)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/master.py", line 415, in _on_forward_log
    logger.handle(record)
Message: "/usr/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 572, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 541, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 384, in format
    return self._fmt % record.__dict__
KeyError: 'user'
Call stack:
  File "/usr/local/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3567, in _broker_main
    _profile_hook('mitogen.broker', self._do_broker_main)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 633, in _profile_hook
    return func(*args)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3554, in _do_broker_main
    self._broker_shutdown()
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3533, in _broker_shutdown
    self._loop_once(max(0, deadline - now()))
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3506, in _loop_once
    self._call(side.stream, func)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3481, in _call
    func(self)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 1705, in on_receive
    self.protocol.on_receive(broker, buf)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 2092, in on_receive
    while self._receive_one(broker):
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 2148, in _receive_one
    self._router._async_route(msg, self.stream)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3308, in _async_route
    return self._invoke(msg, in_stream)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/core.py", line 3248, in _invoke
    fn(msg)
  File "/home/ansible/plugins/mitogen-0.2.9/mitogen/master.py", line 415, in _on_forward_log
    logger.handle(record)
Message: '  return io.open(fd, *args, **kwargs)'
Arguments: ()

```
