### ISSUE TITLE
mitogen 0.2.9 on Ubuntu 22.04 [The Mitogen master process was unable to serve u'ansible.module_utils.distro._distro']

### ISSUE THREAD

**Issue by spidero** [mitogen-hq/mitogen#916]
The full traceback is:
```
Traceback (most recent call last):
  File "/home/spider/.local/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 147, in run
    res = self._execute()
  File "/home/spider/.local/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 665, in _execute
    result = self._handler.run(task_vars=variables)
  File "/opt/ansible/mitogen/ansible_mitogen/mixins.py", line 121, in run
    return super(ActionModuleMixin, self).run(tmp, task_vars)
  File "/home/spider/.local/lib/python3.10/site-packages/ansible/plugins/action/normal.py", line 47, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/opt/ansible/mitogen/ansible_mitogen/mixins.py", line 351, in _execute_module
    self._set_temp_file_args(module_args, wrap_async)
  File "/opt/ansible/mitogen/ansible_mitogen/mixins.py", line 330, in _set_temp_file_args
    self._connection.get_good_temp_dir()
  File "/opt/ansible/mitogen/ansible_mitogen/connection.py", line 775, in get_good_temp_dir
    self._connect()
  File "/opt/ansible/mitogen/ansible_mitogen/connection.py", line 797, in _connect
    self._connect_stack(stack)
  File "/opt/ansible/mitogen/ansible_mitogen/connection.py", line 744, in _connect_stack
    dct = mitogen.service.call(
  File "/opt/ansible/mitogen/mitogen/service.py", line 120, in call
    return call_context.call_service(service_name, method_name, **kwargs)
  File "/opt/ansible/mitogen/mitogen/core.py", line 2276, in call_service
    return recv.get().unpickle()
  File "/opt/ansible/mitogen/mitogen/core.py", line 963, in unpickle
    raise obj
mitogen.core.CallError: exceptions.ImportError: The Mitogen master process was unable to serve u'ansible.module_utils.distro._distro'. It may be a native Python extension, or it may be missing entirely. Check the importer debug logs on the master for more information.
  File "<stdin>", line 3661, in _dispatch_one
  File "<stdin>", line 3648, in _parse_request
  File "<stdin>", line 668, in import_module
  File "<stdin>", line 1510, in load_module
  File "<string>", line 1, in <module>
  File "master:/opt/ansible/mitogen/ansible_mitogen/target.py", line 85, in <module>
    import ansible_mitogen.runner
  File "<stdin>", line 1510, in load_module
  File "<string>", line 1, in <module>
  File "master:/opt/ansible/mitogen/ansible_mitogen/runner.py", line 85, in <module>
    import ansible.module_utils.basic
  File "<stdin>", line 1510, in load_module
  File "<string>", line 1, in <module>
  File "master:/home/spider/.local/lib/python3.10/site-packages/ansible/module_utils/basic.py", line 149, in <module>
    from ansible.module_utils.common.sys_info import (
  File "<stdin>", line 1510, in load_module
  File "<string>", line 1, in <module>
  File "master:/home/spider/.local/lib/python3.10/site-packages/ansible/module_utils/common/sys_info.py", line 10, in <module>
    from ansible.module_utils import distro
  File "<stdin>", line 1510, in load_module
  File "<string>", line 1, in <module>
  File "master:/home/spider/.local/lib/python3.10/site-packages/ansible/module_utils/distro/__init__.py", line 46, in <module>
    from ansible.module_utils.distro import _distro as distro
  File "<stdin>", line 1483, in load_module
```
```
fatal: [pricing_tariff_discounts]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Comment by stop5** [comment]
i have the same error with mitogen 0.3.2 and ansible-core 2.12.5 (ansible 5.7.0)

**Comment by renatopancheri** [comment]
same error with ubuntu 22.04 and mitogen 0.3.1,
the problem seems to be connected with the distro package,
running:
`pip3 install distro==1.4.0 --user`
seems to fix the issue for me,
ubuntu 22.04 comes with the `1.7.0` version

**Comment by spidero** [comment]
thanks, it work
