### ISSUE TITLE
Getting error No module named 'mitogen.select'

### ISSUE THREAD

**Issue by apple4ever** [mitogen-hq/mitogen#945]
* Which version of Ansible are you running?
6.1

* Is your version of Ansible patched in any way?
No

* Are you running with any custom modules, or `module_utils` loaded?
No

* Have you tried the latest master version from Git?
Yes, it is the latest as of this issue

* Do you have some idea of what the underlying problem may be?
No sorry.

* Mention your host and target OS and versions
Host: MacOS 12.4
Target: Debian 11
* Mention your host and target Python versions
Host: Python 3.10

* If reporting a crash or hang in Ansible, please rerun with -vvv and include
  200 lines of output around the point of the error, along with a full copy of
  any traceback or error text in the log. Beware "-vvv" may include secret
  data! Edit as necessary before posting.

```
ansible-playbook [core 2.13.1]
  config file = /Users/apple4ever/Development/config-management/ansible.cfg
  configured module search path = ['/Users/apple4ever/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/apple4ever/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True
Using /Users/apple4ever/Development/config-management/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /Users/apple4ever/Development/config-management/hosts/prod.yml as it did not pass its verify_file() method
script declined parsing /Users/apple4ever/Development/config-management/hosts/prod.yml as it did not pass its verify_file() method
Set default localhost to localhost
Parsed /Users/apple4ever/Development/config-management/hosts/prod.yml inventory source with yaml plugin
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Loading collection community.general from /usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible_collections/community/general
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Loading callback plugin community.general.yaml of type stdout, v2.0 from /usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible_collections/community/general/plugins/callback/yaml.py
Attempting to use 'default' callback.
Skipping callback 'default', as we already have a stdout callback.
Attempting to use 'junit' callback.
Attempting to use 'minimal' callback.
Skipping callback 'minimal', as we already have a stdout callback.
Attempting to use 'oneline' callback.
Skipping callback 'oneline', as we already have a stdout callback.
Attempting to use 'tree' callback.

PLAYBOOK:playbook.yml ******************************************************************************************
Positional arguments: playbooks/playbook.yml
verbosity: 5
remote_user: apple4ever
connection: smart
timeout: 10
become: True
become_method: sudo
become_ask_pass: True
tags: ('all',)
inventory: ('/Users/apple4ever/Development/config-management/hosts/prod.yml',)
forks: 25
1 plays in playbooks/playbook.yml

PLAY [playbook] *************************************************************************************************
ERROR! Unexpected Exception, this is probably a bug: No module named 'mitogen.select'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible/cli/__init__.py", line 601, in cli_executor
    exit_code = cli.run()
  File "/usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible/cli/playbook.py", line 143, in run
    results = pbex.run()
  File "/usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible/executor/playbook_executor.py", line 190, in run
    result = self._tqm.run(play=play)
  File "/usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible/executor/task_queue_manager.py", line 297, in run
    strategy = strategy_loader.get(new_play.strategy, self)
  File "/usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible/plugins/loader.py", line 814, in get
    return self.get_with_context(name, *args, **kwargs).object
  File "/usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible/plugins/loader.py", line 834, in get_with_context
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible/plugins/loader.py", line 802, in _load_module_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple4ever/Development/config-management/plugins/mitogen/ansible_mitogen/plugins/strategy/mitogen_linear.py", line 58, in <module>
    import ansible_mitogen.strategy
  File "/Users/apple4ever/Development/config-management/plugins/mitogen/ansible_mitogen/strategy.py", line 44, in <module>
    import ansible_mitogen.mixins
  File "/Users/apple4ever/Development/config-management/plugins/mitogen/ansible_mitogen/mixins.py", line 52, in <module>
    import mitogen.select
ModuleNotFoundError
```

* If reporting any kind of problem with Ansible, please include the Ansible
  version along with output of "ansible-config dump --only-changed".

```
ansible-community --version
Ansible community version 6.1.0
```

**Comment by apple4ever** [comment]
Confirmed this still happens with version 6.4 and the latest version from master. 

I gotta imagine this is a simple problem no? Or otherwise everybody would be having this issue. But for me, it happens on two different computers.

**Comment by apple4ever** [comment]
I figured this out. Despite pulling the master repo and seeming like it was fine, something got messed up and some files were missing. Once I wiped it and started over, it works now.
