### ISSUE TITLE
Requested entry (plugin_type: connection plugin: mitogen_ssh setting: ssh_args ) was not defined in configuration

### ISSUE THREAD

**Issue by gtirloni** [mitogen-hq/mitogen#954]
* Which version of Ansible are you running?

ansible 6.2.0 / ansible-core 2.13.2

* Is your version of Ansible patched in any way?

No

* Are you running with any custom modules, or `module_utils` loaded?

No

* Have you tried the latest master version from Git?

Yes, commit 8cda5f55375e3c5caa77d900d1bfa90c5fea0094

* Mention your host and target OS and versions
* Mention your host and target Python versions

Host: Fedora 36 with Python 3.10
Target: CentOS 7 with Python 2.7

Traceback

```
The full traceback is:
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/ansible-scripts-MmWCTsjb-py3.10/lib/python3.10/site-packages/ansible/plugins/__init__.py", line 64, in get_option
    option_value = C.config.get_config_value(option, plugin_type=get_plugin_class(self), plugin_name=self._load_name, variables=hostvars)
  File "/home/user/.cache/pypoetry/virtualenvs/ansible-scripts-MmWCTsjb-py3.10/lib/python3.10/site-packages/ansible/config/manager.py", line 436, in get_config_value
    value, _drop = self.get_config_value_and_origin(config, cfile=cfile, plugin_type=plugin_type, plugin_name=plugin_name,
  File "/home/user/.cache/pypoetry/virtualenvs/ansible-scripts-MmWCTsjb-py3.10/lib/python3.10/site-packages/ansible/config/manager.py", line 585, in get_config_value_and_origin
    raise AnsibleError('Requested entry (%s) was not defined in configuration.' % to_native(_get_entry(plugin_type, plugin_name, config)))
ansible.errors.AnsibleError: Requested entry (plugin_type: connection plugin: mitogen_ssh setting: ssh_args ) was not defined in configuration.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/ansible-scripts-MmWCTsjb-py3.10/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 118, in run
    item_results = self._run_loop(items)
  File "/home/user/.cache/pypoetry/virtualenvs/ansible-scripts-MmWCTsjb-py3.10/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 353, in _run_loop
    res = self._execute(variables=task_vars)
  File "/home/user/.cache/pypoetry/virtualenvs/ansible-scripts-MmWCTsjb-py3.10/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 635, in _execute
    result = self._handler.run(task_vars=vars_copy)
  File "/home/user/code/compay/ansible-scripts/vendor/mitogen/ansible_mitogen/mixins.py", line 146, in run
    return super(ActionModuleMixin, self).run(tmp, task_vars)
  File "/home/user/.cache/pypoetry/virtualenvs/ansible-scripts-MmWCTsjb-py3.10/lib/python3.10/site-packages/ansible_collections/ansible/posix/plugins/action/synchronize.py", line 184, in run
    self._connection.get_option('ssh_args'),
  File "/home/user/.cache/pypoetry/virtualenvs/ansible-scripts-MmWCTsjb-py3.10/lib/python3.10/site-packages/ansible/plugins/__init__.py", line 66, in get_option
    raise KeyError(to_native(e))
KeyError: 'Requested entry (plugin_type: connection plugin: mitogen_ssh setting: ssh_args ) was not defined in configuration.'
fatal: [servername.company.net]: FAILED! => {}

MSG:

Unexpected failure during module execution.
```

Additional Information:

The issue happens with the following task (changing `become: false` has no impact):

```yaml
- name: synchronize /usr/share/filebeat/modules/
  become: true
  synchronize:
    src: "usr/share/filebeat/module/{{ item }}"
    dest: "/usr/share/filebeat/module"
    archive: no
    recursive: yes
    delete: yes
    checksum: yes
    use_ssh_args: yes
  with_items: filebeat_modules_install_extra
  notify:
    - restart-filebeat
    - setup-pipelines-filebeat
```

**Comment by dberardo-com** [comment]
same bug here
