### ISSUE TITLE
Error with ansible core 2.11.12 : Error while calling no-reply method mitogen.service.PushFileService.store_and_forward

### ISSUE THREAD

**Issue by donnet** [mitogen-hq/mitogen#986]
Hello,

From time to time I have this sporadic error when running on RHEL 8 : 

ERROR! [mux  3521455] 16:50:12.949418 E mitogen.service.[fork.6774]: While calling no-reply method mitogen.service.PushFileService.store_and_forward
Traceback (most recent call last):
  File "master:/ec/prod/tomcat/playbooks/tomcatdevops/mitogen-0.3.3/mitogen/service.py", line 299, in _invoke
    ret = method(**kwargs)
  File "master:/ec/prod/tomcat/playbooks/tomcatdevops/mitogen-0.3.3/mitogen/service.py", line 820, in store_and_forward
    self._forward(context, path)
  File "master:/ec/prod/tomcat/playbooks/tomcatdevops/mitogen-0.3.3/mitogen/service.py", line 740, in _forward
    context=context
  File "<stdin>", line 1138, in close
  File "<stdin>", line 3149, in del_handler
KeyError: 1001

My configuration is the following on Red Hat Enterprise Linux release 8.7 (Ootpa) : 

ansible-playbook [core 2.11.12] 
  config file = /ec/prod/tomcat/playbooks/tomcatdevops/ansible.cfg
  configured module search path = ['/ec/local/tomcat/home/tomopert/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /ec/local/tomcat/home/tomopert/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /ec/local/tomcat/home/tomopert/.ansible/collections:/usr/share/ansible/collections
  executable location = /ec/local/tomcat/home/tomopert/.local/bin/ansible-playbook
  python version = 3.6.8 (default, Jun 14 2022, 12:54:58) [GCC 8.5.0 20210514 (Red Hat 8.5.0-10)]
  jinja version = 3.0.3
  libyaml = True

By the way, Great library and great speedup !
Thanks a lot !

**Comment by McSim85** [comment]
I have the same issue on
```sh
ansible [core 2.17.10]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```
Ansible contol host and target are Ubuntu 22.04.
Error is:
```
ERROR! [mux  343] 11:20:48.563737 E mitogen.service.[fork.52199]: While calling no-reply method mitogen.service.PushFileService.store_and_forward
Traceback (most recent call last):
  File "master:/usr/local/lib/python3.10/dist-packages/mitogen/service.py", line 291, in _invoke
    ret = method(**kwargs)
  File "master:/usr/local/lib/python3.10/dist-packages/mitogen/service.py", line 814, in store_and_forward
    self._forward(context, path)
  File "master:/usr/local/lib/python3.10/dist-packages/mitogen/service.py", line 733, in _forward
    ).close()
  File "<stdin>", line 1166, in close
  File "<stdin>", line 3307, in del_handler
KeyError: 1001
ERROR! [mux  343] 11:21:01.744858 E mitogen.service.[fork.37176]: While calling no-reply method mitogen.service.PushFileService.store_and_forward
Traceback (most recent call last):
  File "master:/usr/local/lib/python3.10/dist-packages/mitogen/service.py", line 291, in _invoke
    ret = method(**kwargs)
  File "master:/usr/local/lib/python3.10/dist-packages/mitogen/service.py", line 814, in store_and_forward
    self._forward(context, path)
  File "master:/usr/local/lib/python3.10/dist-packages/mitogen/service.py", line 733, in _forward
    ).close()
  File "<stdin>", line 1166, in close
  File "<stdin>", line 3307, in del_handler
KeyError: 1001
```
